name = "ConvertSymbolics"
uuid = "959e4ae2-4b8a-4f0b-bc9b-21a2c241f050"
authors = ["Karl Royen <wessel.karl@googlemail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
