name = "ConvertSymbolics"
uuid = "959e4ae2-4b8a-4f0b-bc9b-21a2c241f050"
authors = ["Karl Royen <wessel.karl@googlemail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[weakdeps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
SymbolicUtilsExt = "SymbolicUtils"
SymbolicsExt = ["Symbolics", "SymbolicUtils"]

[compat]
SymbolicUtils = "3.19.0"
TermInterface = "2.0.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[targets]
test = ["Test", "SymbolicUtils", "Symbolics"]
